/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_joker_multimedia_JniHelper */

#ifndef _Included_com_joker_multimedia_JniHelper
#define _Included_com_joker_multimedia_JniHelper
#ifdef __cplusplus
extern "C" {
#endif

#define TAG "MultiMedia"
JNIEXPORT void JNICALL Java_com_joker_multimedia_JniHelper_nativeInitRecord
        (JNIEnv *, jclass, jobject);
/*
 * Class:     com_joker_multimedia_JniHelper
 * Method:    nativeStartRecord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_joker_multimedia_JniHelper_nativeStartRecord
  (JNIEnv *, jclass);

/*
 * Class:     com_joker_multimedia_JniHelper
 * Method:    nativeStopRecord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_joker_multimedia_JniHelper_nativeStopRecord
  (JNIEnv *, jclass);

/*
 * Class:     com_joker_multimedia_JniHelper
 * Method:    nativePauseRecord
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_joker_multimedia_JniHelper_nativePauseRecord
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_joker_multimedia_JniHelper
 * Method:    nativeSetRecordVolume
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_joker_multimedia_JniHelper_nativeSetRecordVolume
  (JNIEnv *, jclass, jfloat);

#ifdef __cplusplus
}
#endif
#endif
